# Generated by the disassembler -- do not edit.
#
# game.exe is generated, not linked: it carries the segments at the
# addresses the original binary used, which no linker can be told to do.
# They have to be in the executable image rather than any dependency --
# the initial thread's stack is allocated before the loader resolves a
# single import, and it lands in this range if the image does not hold it.
#
# Everything generated therefore compiles into game_code.dll, which the
# stub calls through its import table. That DLL needs no fixed address and
# no linker-specific flags, so it builds with any toolchain.
set(game_STUB_EXE "game.exe")
set(game_CODE_DLL "game_code.dll")
set(game_ENTRY_SYMBOL "gameMain")
set(game_SEGMENT_RANGE "0x400000-0x524000")

# The export name has to match what the stub imports. If a toolchain
# decorates it differently, pin it with a module definition file listing
#     EXPORTS
#         gameMain
