"""Stubs between translated routines and decompiled C++ functions.

A routine the project has decompiled (src/game/decomp/registry.json) is no
longer translated. Every other routine still calls it the translated way --
arguments on the emulated stack and in the emulated registers, then
``sub_xxx(app, cpu)`` -- so it gets a stub under that name which unpacks them
and calls the C++ function:

    void Application::sub_407690(WinApplication* app, x86::CPU& cpu)
    {
        ... = game::PlayerIsDead(win32::fromReg<Player *>(cpu.ecx));
    }

Every routine that is still translated gets the opposite: a C++ function with
the prototype Ghidra gives it, so decompiled code can call it like any other,
which packs the arguments into the CPU and runs the translated routine:

    undefined4 FUN_00409840(int param_1, int param_2)
    {
        cpu.ecx = win32::toReg(param_1); ...
        Application::sub_409840(app, cpu);
        return win32::fromReg<undefined4>(cpu.eax);
    }

Where each argument and the result live comes from Ghidra
(src/game/ghidra/prototypes.json, written by ExportDecompiled.java): the
convention names alone are not enough to go on in this binary.
"""

import json
import os


REGISTRY = 'src/game/decomp/registry.json'
PROTOTYPES = 'src/game/ghidra/prototypes.json'

# What a stub into C++ puts back after the call. The original routine kept to
# its calling convention, and its callers may rely on more than the convention
# promises -- the analysis only guessed it -- so everything that is not the
# result is restored. C++ code never touches these, but a translated routine
# it calls in turn may.
GENERAL_REGISTERS = ['eax', 'ecx', 'edx', 'ebx', 'esi', 'edi', 'ebp']

# Warnings that do not stop a stub from being generated.
TOLERATED = ("the signature is Ghidra's default guess; commit one",)


class CFunctionError(Exception):
    pass


class CFunctions(object):
    def __init__(self, registry=REGISTRY, prototypes=PROTOTYPES):
        self.owned = {}
        if os.path.exists(registry):
            with open(registry) as f:
                for entry, item in json.load(f).get('functions', {}).items():
                    self.owned[int(entry, 16)] = item
        self.prototypes = {}
        if os.path.exists(prototypes):
            with open(prototypes) as f:
                for function in json.load(f)['functions']:
                    self.prototypes[function['entry']] = function
        if self.owned and not self.prototypes:
            raise CFunctionError('%s lists decompiled functions but %s is missing; '
                                 'run ExportDecompiled.java' % (registry, prototypes))

    def owned_entries(self):
        return set(self.owned)

    def write(self, path, application_name, entries, method_names):
        """Write every stub to ``path``.

        ``entries`` are the routines the disassembler translated (or would
        have), ``method_names`` their names in the Application class.
        """
        for entry in sorted(self.owned):
            if entry not in entries:
                raise CFunctionError('0x%08x is decompiled (%s) but the disassembler has no '
                                     'routine there' % (entry, self.owned[entry]['file']))
            proto = self.prototypes.get(entry)
            if proto is None:
                raise CFunctionError('0x%08x is decompiled but Ghidra exported no prototype for it'
                                     % entry)
            problems = [p for p in proto['problems'] if p not in TOLERATED]
            if problems:
                raise CFunctionError('0x%08x %s cannot be called from translated code: %s'
                                     % (entry, proto['name'], '; '.join(problems)))

        with open(path, 'w') as out:
            out.write('// Generated by the disassembler from %s and %s -- do not edit.\n'
                      '//\n'
                      '// Stubs between translated routines and decompiled functions; see\n'
                      '// disasm/cstubs.py.\n\n'
                      '#include "%s.h"\n'
                      '#include <decomp.h>\n\n'
                      'namespace %s\n'
                      '{\n\n' % (REGISTRY, PROTOTYPES, application_name, application_name))
            for entry in sorted(self.prototypes):
                proto = self.prototypes[entry]
                method = method_names.get(entry, 'sub_%x' % entry)
                if entry in self.owned:
                    out.write(self._into_c(proto, method))
                else:
                    out.write(self._into_translated(proto, method if entry in entries else None))
                out.write('\n')
            out.write('}\n')

    # ------------------------------------------------------------------

    @staticmethod
    def _slot(size):
        return (size + 3) & ~3

    def _purge(self, proto):
        if proto['purge'] is not None:
            return proto['purge']
        if proto['cc'] == '__cdecl':
            return 0
        return sum(self._slot(piece['size'])
                   for param in proto['params'] for piece in param['storage'] if 'stack' in piece)

    @staticmethod
    def _registers(storage):
        return [piece['reg'] for piece in storage if 'reg' in piece]

    def _read(self, param):
        """An expression for the argument, read off the CPU in a stub into C++."""
        storage = param['storage']
        t = param['type']
        if len(storage) == 1:
            piece = storage[0]
            if 'stack' in piece:
                return 'static_cast<%s>(app->getMemory<%s>(cpu.esp + 0x%x))' % (t, t, piece['stack'])
            if piece['reg'] == 'st0':
                raise CFunctionError('%s is passed on the x87 stack' % param['name'])
            if piece['shift']:
                return 'win32::fromReg<%s>(x86::reg32(cpu.%s >> %d))' % (t, piece['reg'], 8 * piece['shift'])
            return 'win32::fromReg<%s>(cpu.%s)' % (t, piece['reg'])
        if len(storage) == 2 and all('reg' in p and not p['shift'] for p in storage):
            # Ghidra lists the most significant piece first.
            return 'win32::fromReg<%s>((x86::reg64(cpu.%s) << 32) | cpu.%s)' % (
                t, storage[0]['reg'], storage[1]['reg'])
        raise CFunctionError('%s is split over %s' % (param['name'], storage))

    def _store_result(self, ret):
        storage = ret['storage']
        regs = self._registers(storage)
        if not storage:
            return []
        if regs == ['st0']:
            return ['cpu.fpu.push(x86::Float(double(result)));']
        if regs == ['eax']:
            return ['cpu.eax = win32::toReg(result);']
        if regs == ['edx', 'eax']:
            return ['cpu.edx_eax = win32::toReg64(result);']
        raise CFunctionError('the result is returned in %s' % storage)

    def _into_c(self, proto, method):
        """The translated routine's entry, running the decompiled function."""
        ret = proto['ret']
        outputs = set(self._registers(ret['storage']))
        preserved = [r for r in GENERAL_REGISTERS if r not in outputs]
        args = [self._read(p) for p in proto['params']]
        call = 'game::%s(%s)' % (proto['name'], ', '.join(args))
        lines = ['// 0x%08x  %s  (%s)' % (proto['entry'], proto['declaration'],
                                       self.owned[proto['entry']]['file']),
                 'void Application::%s(WinApplication* app, x86::CPU& cpu)' % method,
                 '{',
                 '    NFS2_USE(app);',
                 '    const x86::reg32 %s;' % ', '.join('saved_%s = cpu.%s' % (r, r) for r in preserved)]
        if ret['storage']:
            lines.append('    const auto result = %s;' % call)
        else:
            lines.append('    %s;' % call)
        lines += ['    cpu.%s = saved_%s;' % (r, r) for r in preserved]
        lines += ['    ' + line for line in self._store_result(ret)]
        lines.append('    cpu.esp += 4 + %d;  // the return address slot, and what the callee pops'
                     % self._purge(proto))
        lines.append('}')
        return '\n'.join(lines) + '\n'

    def _into_translated(self, proto, method):
        """A C++ function with Ghidra's prototype, running the translated routine."""
        problems = [p for p in proto['problems'] if p not in TOLERATED]
        if problems:
            return '// 0x%08x  %s: no stub, %s\n' % (proto['entry'], proto['name'], '; '.join(problems))
        ret = proto['ret']
        stack = [(piece['stack'], param) for param in proto['params']
                 for piece in param['storage'] if 'stack' in piece]
        frame = max([offset + self._slot(param['size']) for offset, param in stack] + [4]) - 4
        lines = ['// 0x%08x' % proto['entry'],
                 proto['declaration'],
                 '{',
                 '    x86::CPU& stub_cpu = win32::currentCpu();',
                 '    win32::WinApplication* stub_app = win32::WinApplication::current();',
                 '    const x86::reg32 stub_esp = stub_cpu.esp;',
                 '    stub_cpu.esp = stub_esp - %d - 4;' % frame]
        for param in proto['params']:
            storage = param['storage']
            if len(storage) != 1:
                return '// 0x%08x  %s: no stub, %s is split over %s\n' % (
                    proto['entry'], proto['name'], param['name'], storage)
            piece = storage[0]
            if 'stack' in piece:
                if param['size'] <= 4:
                    lines.append('    stub_app->getMemory<x86::reg32>(stub_cpu.esp + 0x%x) = win32::toReg(%s);'
                                 % (piece['stack'], param['name']))
                else:
                    lines.append('    stub_app->getMemory<%s>(stub_cpu.esp + 0x%x) = %s;'
                                 % (param['type'], piece['stack'], param['name']))
            elif piece['reg'] != 'st0' and not piece['shift']:
                lines.append('    stub_cpu.%s = win32::toReg(%s);' % (piece['reg'], param['name']))
            else:
                return '// 0x%08x  %s: no stub, %s is passed in %s\n' % (
                    proto['entry'], proto['name'], param['name'], piece)
        if method is not None:
            lines.append('    Application::%s(stub_app, stub_cpu);' % method)
        else:
            # Ghidra has a function here that the disassembler's map does not;
            # whatever routine is registered at the address runs.
            lines.append('    stub_app->dynamic_call(0x%08x, stub_cpu);' % proto['entry'])
        lines.append('    stub_cpu.esp = stub_esp;')
        regs = self._registers(ret['storage'])
        if not ret['storage']:
            pass
        elif regs == ['st0']:
            lines.append('    return %s(double(stub_cpu.fpu.pop()));' % ret['type'])
        elif regs == ['eax']:
            lines.append('    return win32::fromReg<%s>(stub_cpu.eax);' % ret['type'])
        elif regs == ['edx', 'eax']:
            lines.append('    return win32::fromReg<%s>(stub_cpu.edx_eax);' % ret['type'])
        else:
            return '// 0x%08x  %s: no stub, the result is returned in %s\n' % (
                proto['entry'], proto['name'], ret['storage'])
        lines.append('}')
        return '\n'.join(lines) + '\n'
